### ISSUE TITLE
Screenshot of Ansible file?

### ISSUE THREAD

**Issue by mxxcon** [mattchanner/lodestone-theme#1]
The currently included screenshot is of a JavaScript file, not Ansible. Could you please post what it looks like with Ansible?

**Comment by mattchanner** [comment]
Thanks for the issue!

Calling the color scheme Ansible is obviously a cause for confusion as it is not related to the software product with that name, although I am guessing they may share their roots in Orson Scott Card's books :-)

So to avoid any further issues in this area, I have changed the name of the package to lodestone.
